### ISSUE TITLE
Beautify hongbo-wei.github.io

### ISSUE THREAD

**Issue by hongbo-wei** [hongbo-wei/hongbo-wei.github.io#2]
# Improve aesthetics!

## You can do it

![Culture_Matrix_Code_corridor](https://github.com/hongbo-wei/hongbo-wei.github.io/assets/112866063/59ca8a96-36d3-4e28-a6f9-86dd116a760f)

**Comment by hongbo-wei** [comment]
Keep moving forward! Hard work pays off!

**Comment by EiseWilliam** [comment]
I am interested in making a contribution

**Comment by hongbo-wei** [comment]
> I am interested in making a contribution

Hey, would you please tell me why you'd like to do so? :)

**Comment by EiseWilliam** [comment]
New to open source and looking for good first issues or beginner friendly projects to make contributions to.

**Comment by hongbo-wei** [comment]
OK, you are welcome.
